### PR TITLE
Docs update to note switch to unchained randomness

### PR DESCRIPTION
**Pull request by yiannisbot**
Including a note in a couple of central places in the docs to note that docs are updated to include new features, but those are not yet available on mainnet.

### CODE REVIEW

**Review by AnomalRoil — APPROVED** [review]

**Comment by proto-sid** [comment]
May I ask what is the motivation to include this specific section in our public docs?
I am not comfortable about mentioning unreleased features in our public documentation as it does not serve any useful purpose and may only confuse the audience. This would have been helpful if we had some client libraries along with an alpha/beta release of the new Drand binary.

Nonetheless, here is an alternative proposal for the wording (I have avoided mentioning about specific timeline that is many months into the future):

"_As of Q2 2022, the Drand network operated by the [League of Entropy (LoE) (opens new window)](https://blog.cloudflare.com/league-of-entropy/) is running a testnet that implements new features such as support for multiple variable-frequency beacons, and unchained randomness. You can read all the details in [this blogpost (opens new window)](https://drand.love/blog/2022/02/21/multi-frequency-support-and-timelock-encryption-capabilities/). The Drand documentation has been updated to include mention of these features for general awareness even though these features are not available as part of the Drand mainnet. All changes are backward compatible, and the LoE expects these new features to be available in the mainnet towards the end of 2022._"

**Comment by AnomalRoil** [comment]
The further issue is that our current `master` is featuring the changes, but the latest published version `v1.3.2` is not.

Also we should probably add a few extra notes here and there saying that using the drand client to test connection against the LoE nodes won't work because these are not exposed and only the HTTP endpoints are.

**Comment by CluEleSsUK** [comment]
I guess this is a little out of date now :p do we want to update it with details of the real merge or are adding the chain hashes in the other PR enough?

**Comment by CluEleSsUK** [comment]
Revising this after discussion yesterday, I think actually we should close it - the multi-network changes have been in mainnet for a while now.
That said, we should either add a warning or documentation for G1/G2 swap, as it's not anywhere on the website right now

**Pull request closed without merging**
